import 'package:flutter/material.dart';

import '../model/profile_tile_model.dart';

ProfileData ronanProfile = ProfileData(
  name: "Ronan",
  position: "Flutter Developer",
  avatarUrl: 'assets/w5-s2/aang.png',
  tiles: [

    //this datas are generated by Ai because I do not have any idea to put in profile like blah blah blahh...
    TileData(icon: Icons.phone, title: "Phone Number", value: "+123 456 7890"),
    TileData(icon: Icons.location_on, title: "Address", value: "123 Cambodia"),
    TileData(icon: Icons.email, title: "Mail", value: "ronan.ogogr@cadt.edu"),
    TileData(icon: Icons.info, title: "Bio", value: "Hello there"),
    TileData(icon: Icons.cake, title: "Birthday", value: "Jan 1, 2000"),
    TileData(icon: Icons.school, title: "Education", value: "CADT University"),
    TileData(icon: Icons.work, title: "Workplace", value: "Flutter Team"),
    TileData(icon: Icons.language, title: "Languages", value: "English, Khmer"),
    TileData(
      icon: Icons.favorite,
      title: "Hobbies",
      value: "Coding, Reading, Music",
    ),
    TileData(icon: Icons.web, title: "Website", value: "www.ronan.dev"),
  ],
);
